### ISSUE TITLE
有两个问题，希望可以得到解答，谢谢

### ISSUE THREAD

**Issue by zhiyuanding** [yinchuandong/SMO4SVM#1]
有两个问题，希望可以得到解答，谢谢
1. 该代码是否只适合二分类？
2. MySMO类中predict方法，传入的测试数据条数是否只能与训练数据条数相同？（当测试数据条数小于训练数据条数时，predict方法中“sum += model.getAlpha()[j] * model.getY()[j] * kFunction(x[j], x[i], this.gamma);”语句报数组越界错误！）

**Comment by yinchuandong** [comment]
1. SMO本身只是一个二类分类器，SVM多类分类可以基于多个SMO二类分类投票
2. 年代久远，我已经忘了，但理论上来说肯定跟测试数据和训练数据条数没什么关系，你看看是不是哪个dimension的size设置不对。
